tushare:
  token: "${TUSHARE_TOKEN}"

market:
  start_date: "2025-01-01"
  end_date: null
  exchange_scope: "A"
  include_st: true

output:
  stock_basic_file: "data/raw/stock_basic.csv"
  market_cap_file: "data/raw/market_cap.csv"
  daily_dir: "data/raw/daily"

fetch_options:
  update_mode: "incremental"
  retry_times: 3
  sleep_seconds: 0.3 # 每分钟最多40次请求。解决请求过快导致的错误（抱歉，您每分钟最多访问该接口50次，权限的具体详情访问：https://tushare.pro/document/1?doc_id=108。），默认值为0.3秒，这里设置为1.5秒
  batch_size: 200
