def build_candidate_item(row, pick_date: str):
    return {
        "code": row["code"],
        "name": row.get("name"),
        "pick_date": pick_date,
        "strategy": "B1",
        "close": row.get("close"),
        "pct_change": row.get("pct_change"),
        "amplitude_pct": row.get("amplitude_pct"),
        "j_value": row.get("j_value"),
        "white_line": row.get("white_line"),
        "yellow_line": row.get("yellow_line"),
        "white_above_yellow": bool(row.get("white_above_yellow", False)),
        "white_crossed_above_yellow_recently": bool(row.get("white_crossed_above_yellow_recently", False)),
        "white_yellow_distance_pct": row.get("white_yellow_distance_pct"),
        "close_above_white": bool(row.get("close_above_white", False)),
        "close_above_yellow": bool(row.get("close_above_yellow", False)),
        "close_between_white_yellow": bool(row.get("close_between_white_yellow", False)),
        "distance_to_white_pct": row.get("distance_to_white_pct"),
        "distance_to_yellow_pct": row.get("distance_to_yellow_pct"),
        "is_10d_min_volume": bool(row.get("is_10d_min_volume", False)),
        "volume_ratio_vs_prev_day": row.get("volume_ratio_vs_prev_day"),
        "volume_ratio_vs_prev_5d_avg": row.get("volume_ratio_vs_prev_5d_avg"),
        "recent_distribution_within_1m": bool(row.get("recent_distribution_within_1m", False)),
        "recent_distribution_count_1m": row.get("recent_distribution_count_1m"),
    }
